name = "SciMLFromScratch"
uuid = "92c3ecef-e40f-46ab-9b01-ca7e49742dcf"
version = "0.1.0"
authors = ["var-pi <stefanehin4@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.12.0"
StaticArrays = "1.9.16"
