name = "SciMLFromScratch"
uuid = "92c3ecef-e40f-46ab-9b01-ca7e49742dcf"
version = "0.1.0"
authors = ["var-pi <stefanehin4@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BenchmarkTools = "1.6.3"
CairoMakie = "0.15.8"
InteractiveUtils = "1.11.0"
StaticArrays = "1.9.16"
